// Gen-Z / Gen-Alpha Füllwörter und Einschübe 2026
// Erweitert mit allen Begriffen aus dem Jugendsprache-Glossar

const FILLER_WORDS = {
  // Füllwörter die am Satzanfang stehen können
  start: [
    'Digga, ',
    'Bro, ',
    'Bruder, ',
    'Alter, ',
    'Ey, ',
    'Yo, ',
    'No cap, ',
    'Fr fr, ',
    'Real talk, ',
    'Ngl, ',
    'Lowkey, ',
    'Okay but like, ',
    'Wait, ',
    'Ong, ',
    'Bestie, ',
    'Slay, ',
    'Bruh, ',
    'Sheesh, ',
    'Wallah, ',
    'Habibi, ',
    'King, ',
    'Queen, ',
    'Leude, ',
    'Fam, ',
    'Aura check: ',
    'Das crazy, ',
    'Let him cook, ',
    // v6 Erweiterungen
    'Okay hear me out, ',
    'Not gonna lie, ',
    'Plot twist: ',
    'Fun fact: ',
    'Ayo, ',
    'Hör zu, ',
    'Check das: ',
    'Stell dir vor, ',
    'Also basically, ',
    'Tbh, ',
    'Ich sag mal so, ',
    'Ey warte, ',
    'Kurze Ansage: ',
    'Kleiner Vibe check: ',
    'Straight up, ',
    'Deadass, ',
    'No front, ',
    'Ohne Witz, ',
    'Kein Flex, ',
    'Achtung Brainrot: ',
    'Real ones wissen: ',
    'Sigma take: ',
    'Hot take: ',
    'Unpopular opinion: ',
    'POV: ',
    'Bro literally, ',
    'Das ist so, ',
    'Yoo, ',
    'Okay krass, ',
    'Also hört mal, ',
    'W Aussage: ',
    'Mois, ',
    'Yalla, ',
    'Pookie, ',
  ],

  // Füllwörter die in der Mitte eines Satzes stehen können
  mid: [
    ' lowkey ',
    ' highkey ',
    ' literally ',
    ' fr ',
    ' ngl ',
    ' no cap ',
    ' halt ',
    ' irgendwie ',
    ', digga, ',
    ', bro, ',
    ', alter, ',
    ' ong ',
    ' deadass ',
    ' straight up ',
    ', und so, ',
    ' oder so ',
    ' safe ',
    ' real talk ',
    ' unironisch ',
    ' on god ',
    ' periodt ',
    ' das crazy ',
    ' its giving ',
    // v6 Erweiterungen
    ', you know, ',
    ' basically ',
    ', hear me out, ',
    ' not gonna lie ',
    ', tbh, ',
    ' at this point ',
    ' for real for real ',
    ', kein Flex, ',
    ' wenn man so will ',
    ', respectfully, ',
    ' auf einem anderen Level ',
    ', und ich sag das mit voller Überzeugung, ',
    ' – und ja das mein ich so – ',
    ', also quasi, ',
    ' im Grunde genommen ',
    ', no front, ',
    ' ohne cap ',
    ', fun fact, ',
    ' ich schwör dir ',
    ', wait for it, ',
    ', und das ist das Ding, ',
  ],

  // Füllwörter die am Satzende stehen können
  end: [
    ' fr',
    ' ngl',
    ' no cap',
    ', digga',
    ', bro',
    ', alter',
    ', ehrlich jetzt',
    ', kein Ding',
    ', real talk',
    ' ong',
    ', weißte',
    ', verstehste',
    ', safe',
    ', on god',
    ', und so',
    ', oder so',
    ', wallah',
    ' tbh',
    ' istg',
    ', ich schwör',
    ', periodt',
    ', Mashallah',
    ' fr fr',
    ', Habibi',
    ', no cap fr',
    ', das crazy',
    ', six seven',
    ', Aura +100',
    // v6 Erweiterungen
    ', deadass',
    ', straight up',
    ' und das ist facts',
    ', kannste glauben',
    ', trust',
    ', trust me bro',
    ', ist so',
    ', you feel me',
    ', keine Frage',
    ', ungelogen',
    ', ich lüg nicht',
    ' (real)',
    ', das muss man anerkennen',
    ', punkt',
    ', ende',
    ', mic drop',
    ', case closed',
    ', that\'s it',
    ', that\'s the tea ☕',
    ', respectfully',
    ', lowkey tho',
    ', highkey tho',
    ', not even capping',
    ', on everything',
    ', und damit mein ich alles',
    ', wer\'s nicht glaubt',
    ', swear down',
    ', rede!',
    ', mois',
    ', pookie',
    ', yalla',
    ', Aura +1000',
    ', iykyk',
  ],
};

// Gen-Alpha spezifische Einschübe (TikTok / Roblox / Fortnite / 2026 Trends)
const GEN_ALPHA_EXTRAS = [
  'Skibidi ',
  'Rizz-mäßig ',
  'Sigma ',
  'Ohio-mäßig ',
  'Gyatt ',
  'Fanum tax ',
  'Literally so ',
  'Sus ',
  'Bussin ',
  'Slay ',
  'Periodt ',
  'Its giving ',
  'Main character energy ',
  'Understood the assignment ',
  'Ate and left no crumbs ',
  'Rent free ',
  'Locked in ',
  'Delulu ',
  'Its giving Era ',
  'Vibe check: ',
  'No cap fr fr ',
  'POV: ',
  'Bro is cooked ',
  'Six seven ',
  'Aura +100 ',
  'Canon event: ',
  'Side quest: ',
  'Let him cook ',
  'Das crazy ',
  'Chopped ',
  // v6 Erweiterungen
  'Mewing 🤫 ',
  'Glazing alert: ',
  'Yapping detected: ',
  'Pick me energy: ',
  'Red flag: 🚩 ',
  'Green flag: 🟢 ',
  'Plot armor activated: ',
  'NPC behavior: ',
  'Sigma grindset: ',
  'Beta move: ',
  'Alpha energy: ',
  'Brainrot incoming: ',
  'Looksmaxxing: ',
  'Touch grass moment: ',
  'Chronically online: ',
  'Absolutely unhinged: ',
  'Erm what the sigma: ',
  'Bro thinks he\'s him: ',
  'Living rent free: ',
  'W rizz: ',
  'Negative aura: ',
  'Aura +1000: ',
  'Top tier: ',
  'S-tier: ',
  'Ratio incoming: ',
  'Chat is this real: ',
  'Bro woke up and chose violence: ',
  'Say it louder: ',
  'The way that... ',
  'Not me reading this... ',
];

// Satz-Einschübe die zwischen Sätzen eingefügt werden (bei hoher Intensität)
const SENTENCE_INTERJECTIONS = [
  'Sheesh.',
  'No cap.',
  'Fr fr.',
  'Wild.',
  'Ong.',
  'Slay.',
  'Periodt.',
  'Real.',
  'Facts.',
  'Based.',
  'Respekt.',
  'Ehre.',
  'W.',
  'Mood.',
  'Vibe.',
  'Das crazy.',
  'Bruh.',
  'Cooked.',
  'Six seven.',
  'Aura.',
  'Canon.',
  'Let him cook.',
  // v6 Erweiterungen
  'Tuff.',
  'Rede!',
  'Valid.',
  'Not gonna lie.',
  'Say less.',
  'Heard.',
  'Bet.',
  'Noted.',
  'Big if true.',
  'Rent free.',
  'Yikes.',
  'Oof.',
  'RIP.',
  'Pain.',
  'It\'s giving.',
  'Main character moment.',
  'Plot twist.',
  'Red flag tbh.',
  'Touch grass.',
  'Absolutely unhinged.',
  'Ratio.',
  'Cope.',
  'Bro what.',
  'LMAO.',
  'I can\'t.',
  'Dead. 💀',
  'We move.',
  'L.',
  'That\'s crazy.',
  'Chat.',
];

/**
 * Gibt ein zufälliges Füllwort für die angegebene Position zurück
 * @param {'start'|'mid'|'end'} position
 * @param {number} intensity 10-100
 */
function getRandomFiller(position, intensity) {
  const pool = FILLER_WORDS[position];
  if (!pool) return '';

  // Bei höherer Intensität auch Gen-Alpha Extras einstreuen
  if (intensity > 60 && position === 'start' && Math.random() < 0.3) {
    const extra = GEN_ALPHA_EXTRAS[Math.floor(Math.random() * GEN_ALPHA_EXTRAS.length)];
    return extra;
  }

  return pool[Math.floor(Math.random() * pool.length)];
}

/**
 * Gibt einen zufälligen Satz-Einschub zurück
 */
function getRandomInterjection() {
  return SENTENCE_INTERJECTIONS[Math.floor(Math.random() * SENTENCE_INTERJECTIONS.length)];
}

/**
 * Entscheidet ob ein Füllwort eingefügt werden soll basierend auf Intensität
 * @param {number} intensity 10-100
 */
function shouldInsertFiller(intensity) {
  // Bei 100% Intensität: 60% Chance, bei 10%: 6% Chance
  return Math.random() < (intensity / 100) * 0.6;
}
